<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Image\ArmorIcon.png" />
      <None Remove="Image\HealingPointIcon.png" />
      <None Remove="Image\WeaponIcon.png" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Images\HealingPointIcon.png" />
      <None Remove="Images\WeaponIcon.png" />
      <None Remove="Images\ArmorIcon.png" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Images\ArmorIcon.png" />
      <Resource Include="Images\WeaponIcon.png" />
      <None Remove="Images\ChestIcon.png" />
      <Resource Include="Images\ChestIcon.png" />
      <None Remove="Images\EnemyIcon.png" />
      <Resource Include="Images\EnemyIcon.png" />
      <None Remove="Images\HealPointIcon.png" />
      <Resource Include="Images\HealPointIcon.png" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChestOrMonster\ChestOrMonster.csproj" />
    </ItemGroup>

</Project>
